language: c
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  - wget https://downloads.arduino.cc/arduino-1.8.1-linux64.tar.xz
  - tar xf arduino-1.8.1-linux64.tar.xz
  - sudo mv arduino-1.8.1 /usr/local/share/arduino
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino
install:
  #- arduino --install-boards http://arduino.esp8266.com/stable/package_esp8266com_index.json
  - arduino --install-library "Adafruit GFX Library,ArduinoJson,Adafruit SSD1306,DHT sensor library,Adafruit Unified Sensor"
script:
  - arduino --verify --board esp8266:esp8266:huzzah $PWD/AdvancedWebServerOLED/AdvancedWebServerOLED.ino
notifications:
  email:
    on_success: change
    on_failure: change
