env:
  global:
    - CODECOV_TOKEN=:secret:Q0TkVdbWEq7bEv6q6oVNbRosgDdfyzz7kNB3EXgdwmzAJYP+bjxiSl0KoZIMuhvf1JXjXdXGEF1tZB13ja5tulznTuVk+D9EorZ/RofpMew=
language: c
before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
install:
  - arduino --install-library 'Adafruit GFX Library,ArduinoJson,Adafruit SSD1306,DHT sensor library,Adafruit Unified Sensor'
script:
  - build_platform esp8266
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    on_success: change
    on_failure: change
