env:
  global:
    - CODECOV_TOKEN=:secret:Q0TkVdbWEq7bEv6q6oVNbRosgDdfyzz7kNB3EXgdwmzAJYP+bjxiSl0KoZIMuhvf1JXjXdXGEF1tZB13ja5tulznTuVk+D9EorZ/RofpMew=
language: c
before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
install:
  #- arduino --install-boards http://arduino.esp8266.com/stable/package_esp8266com_index.json
  #- git clone https://github.com/bblanchon/ArduinoJson /usr/local/share/arduino/libraries/ArduinoJson
  #- rm -rf /usr/local/share/arduino/libraries/ArduinoJson/.github
  - arduino --install-library 'Adafruit GFX Library,ArduinoJson,Adafruit SSD1306,DHT sensor library,Adafruit Unified Sensor'
  #- arduino --pref "boardsmanager.additional.urls=http://arduino.esp8266.com/stable/package_esp8266com_index.json" --save-prefs
  # - arduino --board esp8266:esp8266:generic --save-prefs
  #- arduino --install-boards esp8266:esp8266

script:
  #- arduino --verify --board esp8266:esp8266:huzzah $PWD/AdvancedWebServerOLED/AdvancedWebServerOLED.ino
  - build_platform esp8266
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    on_success: change
    on_failure: change
