language: python
python:
    - "2.7"
sudo: false
cache:
    directories:
        - "~/.platformio"
script:
    - platformio run
install:
    - pip install -U platformio
    - platformio lib -g install 1

script:
    - cp ./src/Pubvars.h.temp ./src/Pubvars.h
    - platformio ci --project-conf=platformio.ini ./src
